version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "localstack-example"

[default.build.parameters]
cached = true
parallel = true
use_container = true

[default.deploy.parameters]
confirm_changeset = false
resolve_s3 = true
region = "us-west-2"